### ISSUE TITLE
2.2 Plan

### ISSUE THREAD

**Issue by devcatalin** [kubeshop/monokle#3933]
## Helm
- [x] #3251 @mortada-codes 
   - [x] Manage helm repositories (add / remove) 
   - [x] Search for helm charts
   - [x] Install found helm chart to the cluster
   - [x] Download found helm chart locally
   
## Cluster
- [x] #3547
- [x] #3931 @topliceanurazvan 
- [ ] Add `Diff` action in cluster actions @topliceanurazvan 
- [ ] Logs improvements @topliceanurazvan 
   - [ ] #3398 
   - [ ] #3313 
   - [x] #3826
   - [ ] #3814 
- [x] Accordion #3934
- [x] Helm panel #1983
   - [x] List existing helm charts installed in the cluster
   - [x] Actions to uninstall existing helm charts
   - [x] Info panel for Helm chart
      - [x] Show revisions

## Validation
- [x] Configuration panel for Resource Links validator #3840 @topliceanurazvan 
   - [ ] Consider a setting for: #3553 
- [x] Ensure that Desktop can use policies defined in Cloud - #3995 
- [x] Support for plugins as in Cloud #3254 @devcatalin 
- [ ] UI improvements #3443

## UI improvements
- [ ] Split local & cluster mode #3757 
   - [ ] Decide how the Validation panel should work
   - [ ] Remove explorer logic related to "active" storage? (we still need it for previews?)
- [ ] Local to cluster resource matching functionality #3932
- [ ] Make it easier to preview multiple values files

## Other
- [x] Provide sample project #3495 @topliceanurazvan 
- [ ] Project "Dashboard"
- [x] In-app "RSS-feed" #3935
- [ ] Multi-resource actions #3085 @devcatalin 

## Nice to have
- [x] #3656
- [ ] New Events tab 
   - [ ] #3637
